---
apiVersion: v1
kind: Namespace
metadata:
  name: random-counter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: random-counter
  labels:
    name: random-counter
  namespace: random-counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: random-counter
    spec:
      containers:
        - name: random-log-counter
          image: gcr.io/davids-demo-environment/random_log_counter:v1
          imagePullPolicy: Always
---