apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: sock-chaos
  namespace: sock-shop
spec:
  chaosType: 'infra'  # It can be app/infra
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ""
  appinfo:
    appns: sock-shop
    applabel: 'name=carts-db'
    appkind: deployment
  chaosServiceAccount: sock-shop-chaos-engine
  monitoring: true
  components:
    runner:
      image: "litmuschaos/chaos-executor:1.0.0"
      type: "go"
  # It can be delete/retain
  jobCleanUpPolicy: delete
  experiments:
    - name: cpu-hog
      spec:
        components:
           # set chaos duration (in sec) as desired
          - name: TOTAL_CHAOS_DURATION
            value: '60'
          # set chaos platform as desired
          - name: PLATFORM
            value: 'GKE'
          # chaos lib used to inject the chaos
          - name: LIB
            value: 'litmus'