apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kafka-chaos
  namespace: kafka
spec:
  # It can be true/false
  annotationCheck: 'true'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ""
  engineState: 'active'
  appinfo:
    appns: kafka
    applabel: 'app=cp-kafka'
    appkind: statefulset
  chaosServiceAccount: kafka-chaos-engine
  monitoring: true
  # It can be delete/retain
  jobCleanUpPolicy: delete
  experiments:
    - name: kafka-broker-pod-failure
      spec:
        components:
          env: 
            # choose based on available kafka broker replicas
            - name: KAFKA_REPLICATION_FACTOR
              value: '3'

            # get via "kubectl get pods --show-labels -n <kafka-namespace>"
            - name: KAFKA_LABEL
              value: 'app=cp-kafka'

            - name: KAFKA_NAMESPACE
              value: 'kafka'

            # get via "kubectl get svc -n <kafka-namespace>"
            - name: KAFKA_SERVICE
              value: 'kafka-cluster-cp-kafka-headless'

            # get via "kubectl get svc -n <kafka-namespace>
            - name: KAFKA_PORT
              value: '9092'

            # in milliseconds
            - name: KAFKA_CONSUMER_TIMEOUT
              value: '70000'

            - name: ZOOKEEPER_NAMESPACE
              value: 'kafka'

            # get via "kubectl get pods --show-labels -n <zk-namespace>"
            - name: ZOOKEEPER_LABEL
              value: 'app=cp-zookeeper'

            # get via "kubectl get svc -n <zk-namespace>
            - name: ZOOKEEPER_SERVICE
              value: 'kafka-cluster-cp-zookeeper-headless'

            # get via "kubectl get svc -n <zk-namespace>
            - name: ZOOKEEPER_PORT
              value: '2181'

            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '300'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '20'

            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: "false"

            - name: DEFAULT_GATHERING
              value: "explicit"
