apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: sock-chaos
  namespace: sock-shop
spec:
  # It can be app/infra
  chaosType: 'app'
  #ex. values: sock-shop:name=carts
  auxiliaryAppInfo: ""
  components:
    runner:
      image: "litmuschaos/chaos-executor:1.0.0"
      type: "go"
  # It can be delete/retain
  jobCleanUpPolicy: delete
  monitoring: true
  appinfo:
    appns: sock-shop
    # FYI, To see app label, apply kubectl get pods --show-labels
    # unique-label of the application under test (AUT)
    applabel: "name=carts-db"
    appkind: deployment
  chaosServiceAccount: sock-shop-chaos-engine
  experiments:
    - name: pod-delete
      spec:
        components:
           # set chaos duration (in sec) as desired
          - name: TOTAL_CHAOS_DURATION
            value: '30'
          # set chaos interval (in sec) as desired
          - name: CHAOS_INTERVAL
            value: '10'
          # pod failures without '--force' & default terminationGracePeriodSeconds
          - name: FORCE
            value: "false"