---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sock-shop-chaos-engine
  namespace: sock-shop
  labels:
    app: sock-shop
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sock-shop-chaos-engine
  namespace: sock-shop
rules:
- apiGroups: ["", "apps", "batch", "litmuschaos.io"]
  resources: ["daemonsets", "jobs", "pods", "pods/exec", "chaosengines", "chaosexperiments", "chaosresults"]
  verbs: ["create","list","get","patch","update","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sock-shop-chaos-engine
  namespace: sock-shop
roleRef:
  kind: Role
  name: sock-shop-chaos-engine
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sock-shop-chaos-engine
  namespace: sock-shop 
